f=open('textFile.txt','w')
f.writelines(['hi there','how are you?'])
f.close()
f=open('textFile.txt','r+')
str=f.read(15)
print('string str\t:',str)
pos=f.tell()
print('current position\t:',pos)
str1=f.read(5)
print('str1\t:',str1)
pos=f.seek(0,0)
print('current position\t:',pos)
str=f.read(20)
print('again read string is :',str)
f.close()

